apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: server
          image: busybox
          command: ["sh", "-c", "echo 'hello from replica' > /tmp/index.html && httpd -f -p 8080 -h /tmp"]
